# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Y:\tmp\fossil\wd\pymcadp\2017fall\ui\Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(380, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(380, 380))
        Dialog.setMaximumSize(QtCore.QSize(380, 380))
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 2)
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_9.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 2, 1, 2)
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_11.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 1, 4, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.seven = QtWidgets.QPushButton(Dialog)
        self.seven.setMinimumSize(QtCore.QSize(50, 50))
        self.seven.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 2, 1, 1, 1)
        self.eight = QtWidgets.QPushButton(Dialog)
        self.eight.setMinimumSize(QtCore.QSize(50, 50))
        self.eight.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 2, 2, 1, 1)
        self.nine = QtWidgets.QPushButton(Dialog)
        self.nine.setMinimumSize(QtCore.QSize(50, 50))
        self.nine.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 2, 3, 1, 1)
        self.divide = QtWidgets.QPushButton(Dialog)
        self.divide.setMinimumSize(QtCore.QSize(50, 50))
        self.divide.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.divide.setFont(font)
        self.divide.setObjectName("divide")
        self.gridLayout.addWidget(self.divide, 2, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_6.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 5, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_7.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 3, 0, 1, 1)
        self.four = QtWidgets.QPushButton(Dialog)
        self.four.setMinimumSize(QtCore.QSize(50, 50))
        self.four.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 3, 1, 1, 1)
        self.five = QtWidgets.QPushButton(Dialog)
        self.five.setMinimumSize(QtCore.QSize(50, 50))
        self.five.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 3, 2, 1, 1)
        self.six = QtWidgets.QPushButton(Dialog)
        self.six.setMinimumSize(QtCore.QSize(50, 50))
        self.six.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 3, 3, 1, 1)
        self.multiply = QtWidgets.QPushButton(Dialog)
        self.multiply.setMinimumSize(QtCore.QSize(50, 50))
        self.multiply.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.multiply.setFont(font)
        self.multiply.setObjectName("multiply")
        self.gridLayout.addWidget(self.multiply, 3, 4, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_13.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 5, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 4, 0, 1, 1)
        self.one = QtWidgets.QPushButton(Dialog)
        self.one.setMinimumSize(QtCore.QSize(50, 50))
        self.one.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 4, 1, 1, 1)
        self.two = QtWidgets.QPushButton(Dialog)
        self.two.setMinimumSize(QtCore.QSize(50, 50))
        self.two.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 4, 2, 1, 1)
        self.three = QtWidgets.QPushButton(Dialog)
        self.three.setMinimumSize(QtCore.QSize(50, 50))
        self.three.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 4, 3, 1, 1)
        self.minus = QtWidgets.QPushButton(Dialog)
        self.minus.setMinimumSize(QtCore.QSize(50, 50))
        self.minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 4, 4, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(Dialog)
        self.pushButton_24.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_24.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 4, 5, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 5, 0, 1, 1)
        self.zero = QtWidgets.QPushButton(Dialog)
        self.zero.setMinimumSize(QtCore.QSize(50, 50))
        self.zero.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 5, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_22.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 5, 2, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(Dialog)
        self.pushButton_25.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_25.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 5, 3, 1, 1)
        self.plus = QtWidgets.QPushButton(Dialog)
        self.plus.setMinimumSize(QtCore.QSize(50, 50))
        self.plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plus.setFont(font)
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 5, 4, 1, 1)
        self.equal = QtWidgets.QPushButton(Dialog)
        self.equal.setMinimumSize(QtCore.QSize(50, 50))
        self.equal.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.gridLayout.addWidget(self.equal, 5, 5, 1, 1)
        self.display = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.display.setFont(font)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setObjectName("display")
        self.gridLayout.addWidget(self.display, 0, 0, 1, 6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_2.setText(_translate("Dialog", "PushButton"))
        self.pushButton_9.setText(_translate("Dialog", "PushButton"))
        self.pushButton_11.setText(_translate("Dialog", "PushButton"))
        self.pushButton_3.setText(_translate("Dialog", "PushButton"))
        self.seven.setText(_translate("Dialog", "7"))
        self.eight.setText(_translate("Dialog", "8"))
        self.nine.setText(_translate("Dialog", "9"))
        self.divide.setText(_translate("Dialog", "/"))
        self.pushButton_6.setText(_translate("Dialog", "PushButton"))
        self.pushButton_7.setText(_translate("Dialog", "PushButton"))
        self.four.setText(_translate("Dialog", "4"))
        self.five.setText(_translate("Dialog", "5"))
        self.six.setText(_translate("Dialog", "6"))
        self.multiply.setText(_translate("Dialog", "*"))
        self.pushButton_13.setText(_translate("Dialog", "PushButton"))
        self.pushButton_4.setText(_translate("Dialog", "PushButton"))
        self.one.setText(_translate("Dialog", "1"))
        self.two.setText(_translate("Dialog", "2"))
        self.three.setText(_translate("Dialog", "3"))
        self.minus.setText(_translate("Dialog", "-"))
        self.pushButton_24.setText(_translate("Dialog", "PushButton"))
        self.pushButton_5.setText(_translate("Dialog", "PushButton"))
        self.zero.setText(_translate("Dialog", "0"))
        self.pushButton_22.setText(_translate("Dialog", "PushButton"))
        self.pushButton_25.setText(_translate("Dialog", "PushButton"))
        self.plus.setText(_translate("Dialog", "+"))
        self.equal.setText(_translate("Dialog", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

